name: Generate Images

on:
  workflow_dispatch:

jobs:
  Build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        versions:
          - ecosystem: python
            package:  python3
            tag: crda/python3
            path: Dockerfiles/Dockerfile.python
          - ecosystem: python
            package:  python36
            tag: crda/python36
            path: Dockerfiles/Dockerfile.python
          - ecosystem: python
            package:  python38
            tag: crda/python38
            path: Dockerfiles/Dockerfile.python
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push ${{ matrix.ecosystem }}-${{ matrix.version }}
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        VERSION: ${{ matrix.version }}
        ECOSYSTEM : ${{ matrix.ecosystem }}
      with:
        file: ./${{ matrix.path }}}
        push: true
        tags: ${{ matrix.tag }}
        build-args: ECOSYSTEM_VERSION=$VERSION