name: Generate Images

on:
  workflow_dispatch:

jobs:
  Build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        versions:
          - ecosystem: python
            package:  python3
          - ecosystem: python
            package:  python36
          - ecosystem: python
            package:  python38
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push ${{ matrix.ecosystem }}-${{ matrix.version }}
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dependency-analytics/${{ matrix.version }}:latest
        build-args: ECOSYSTEM_VERSION=${{ matrix.version }}